### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by Koziar**

### CODE REVIEW

**Review by Ldaxar — CHANGES_REQUESTED** [review]
You shouldn't change the test data. Plz revert test data to the previous state and rewrite your changes to fit old tests.

**Comment by Koziar** [comment]
ok

**Comment by Koziar** [comment]
Reverted test data to the previous state and fixed bug so tests pass

screen shot 2017-12-11 at 17 57 21

**Review by Ldaxar — APPROVED** [review]
Overall good job.

-        Integer status = restTemplate.getForObject("http://46.101.28.25:8080/latest", Integer.class);
 -        return status;
 -        
 +		return restTemplate.getForObject("http://46.101.28.25:8080/latest", Integer.class);

It's not like I want to be a smart ass but changes like this are bad. On lining is cool (I love to make code as small as possible) but sad reality is that such code is harder to read and edit - therefore irritating to work with and harder to maintain.

**Pull request merged**
